# Production context: all deploys from the main branch 
# will inherit these settings.
[build]
  publish = "."
  command = "npm run build"

# Set up the functions directory
[functions]
  directory = "server/functions"
  node_bundler = "esbuild"

# Individual function settings
[[functions]]
  name = "processImage"
  external_node_modules = ["canvas"]
  [functions.processImage]
    timeout = 30

[[functions]]
  name = "imageSync"
  [functions.imageSync]
    timeout = 20

# Header configs
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' *.netlify.app; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://unpkg.com https://www.googletagmanager.com https://static.cloudflareinsights.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://unpkg.com https://fonts.googleapis.com https://cdn.jsdelivr.net; img-src 'self' data: blob: https://cdn.jsdelivr.net; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; frame-src 'self'; form-action 'self';"

# Redirect and rewrite rules
[[redirects]]
  from = "/.netlify/functions/processImage"
  to = "/.netlify/functions/processImage"
  status = 200

[[redirects]]
  from = "/.netlify/functions/imageSync/*"
  to = "/.netlify/functions/imageSync/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 